data_module:
  df_path: null #'/blue/hennig/sam.dong/DIS_GNN/dis_gnn/data/data/df_transition_metal_oxide.pkl'
  composition: null #["O","Sc","Ti","V","Cr","Mn","Fe","Co","Ni","Cu","Zn","Y","Zr","Nb","Mo","Tc","Ru","Rh","Pd","Ag","Cd","Hf","Ta","W","Re","Os","Ir","Pt","Au","Hg","Rf","Db","Sg","Bh","Hs","Mt","Ds","Rg","Cn"]  
  structures_path: '/blue/hennig/sam.dong/mp_api/mp_api_09_25_2025.pkl'
  cutoff: 4.0
  property_name: 'band_gap'
  save_path: '/blue/hennig/sam.dong/DIS_GNN/dis_gnn/data/data/df_transition_metal_oxide.pkl'
model:
  checkpoint_path: '/blue/hennig/sam.dong/disordered_gnn/checkpoints/'
  batch_size: 4
  num_epochs: 750
  criterion: 'bce'
  optimizer: 'adam'
  lr: 0.0000025
  test_val_split: 0.9
  n_hid: 32
  gnn:
    n_layers: 3
    dropout: 0.5
    n_resid_layers: 3
    n_mlp_layers: 3
  classifier:
    hidden_dim: 32
